### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by learnerLj** [lmy375/peth#5]
When I download the source code for contract(https://bscscan.com/address/0x9059f2f644402db18155b7917762823a58962397) at BSC, it throws an error:
````
Error:  [Errno 13] Permission denied: '/Users'
Traceback (most recent call last):
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/site-packages/peth-0.1.3-py3.10.egg/peth/core/console.py", line 58, in onecmd
    return super().onecmd(line)
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/site-packages/peth-0.1.3-py3.10.egg/peth/core/console.py", line 1331, in do_download_source
    ret = self.peth.scan.download_source(addr, output_dir)
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/site-packages/peth-0.1.3-py3.10.egg/peth/eth/scan.py", line 193, in download_source
    os.makedirs(parent_dir)
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 3 more times]
  File "/home/learner/tools/anaconda3/envs/slither/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users'
```
However, it works when downloading other contracts with different addresses.

**Comment by lmy375** [comment]
Nice catch ! I fixed at https://github.com/lmy375/peth/commit/95571e28d38b4e8f6614c37ebc4d17ffc6e27b83
